# Generated by Django 5.1.7 on 2025-05-18 22:35

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='dietary_restrictions',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='loyalty_points',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='shift_preferences',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
